 const data = [
	{
		id:"1",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"2",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"3",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"4",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"5",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"6",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"7",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"8",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"9",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"10",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"11",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"12",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"13",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"14",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"15",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"16",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"17",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"18",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"19",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"20",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"21",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"22",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"23",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"24",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"25",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"26",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"27",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"28",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"29",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"30",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"31",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"32",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"33",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"34",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"35",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"36",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"37",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"38",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"39",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"40",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"41",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"42",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"43",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"44",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"45",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"46",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"47",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"48",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"49",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"50",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"51",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"52",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"53",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"54",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"55",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"56",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"57",
		name:"Toyota",
		year:2019,
		image:"images/suv.jpg",
		price:1200,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"58",
		name:"Hyundai",
		year:2020,
		image:"images/sedan.jpg",
		price:700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
	{
		id:"59",
		name:"Mercedes",
		year:2019,
		image:"images/hatcback.jpg",
		price:1000,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},	
	{
		id:"60",
		name:"Ferrari",
		year:2020,
		image:"images/sedan.jpg",
		price:1700,
		people: 2,
		fuel: "hybrid",
		range: 10,
		type:"automatic",
	},
 ]

 export default data